export const ADD_IPPON = 'ADD_IPPON'
export const REMOVE_IPPON = 'REMOVE_IPPON'
export const SET_WIN = 'SET_WIN'
export const SET_LOSE = 'SET_LOSE'
export const SET_TIE = 'SET_TIE'
export const RESET_OUTCOME = 'RESET_OUTCOME'
