export const MEN = 'men'
export const KOTE = 'kote'
export const DOU = 'dou'
export const TSUKI = 'tsuki'
export const RED = 'red'
export const WHITE = 'white'
export const HANSOKU = 'hansoku'
export const PENALTY = 'penalty'
export const WIN = 'win'
export const LOSE = 'lose'
export const TIE = 'tie'
export const ROUNDROBIN = 'Round Robin'
/* For simulations */
export const TIEMATCH = 'TieMatch'
export const ONEPOINTMATCH = 'OnePointMatch'
export const TWOPOINTMATCH = 'TwoPointMatch'
export const TWOTOONEMATCH = 'TwoToOneMatch'
